### ISSUE TITLE
[BUG] Price difference between ETH on the tokenpair page and ETH in the top left corner

### ISSUE THREAD

**Issue by MooncatDEXT** [dextools-io/community-requests#100]
### Steps

...
There is a price difference between these ETH values although it should be the same (see picture).

<img width="989" alt="Screenshot 2024-03-10 at 20 39 48" src="https://github.com/dextools-io/community-requests/assets/155443659/446e54a8-f920-4e2d-9f3d-2bb64585542a">

https://www.dextools.io/app/en/ether/pair-explorer/0x0d4a11d5eeaac28ec3f61d100daf4d40471f1852?t=1710099576946

### Which device are you using

- [X] Any
- [ ] Desktop Windows
- [ ] Desktop MacOS
- [ ] Desktop Linux
- [ ] Mobile browser
- [ ] App

### (if aplicable) What mobile OS device are you using?

None

**Comment by Sanher** [comment]
Every pool can have different prices at current moment. Will not consider this as a bug. Closing it. FYI @MooncatDEXT
