### ISSUE TITLE
[BUG] Swap button shows error on DUH token on BASE

### ISSUE THREAD

**Issue by MooncatDEXT** [dextools-io/community-requests#103]
### Steps

...
Swap button is red and returns 'error' warning. It's not possible to swap this token.

https://www.dextools.io/app/en/base/pair-explorer/0x50f16aab823bc786f9c2647ef99599931c6c12ac

<img width="857" alt="Screenshot 2024-03-14 at 02 54 20" src="https://github.com/dextools-io/community-requests/assets/155443659/9cc5f6c1-c2cd-46a7-8390-3494ab15808a">

### Which device are you using

- [X] Any
- [ ] Desktop Windows
- [ ] Desktop MacOS
- [ ] Desktop Linux
- [ ] Mobile browser
- [ ] App

### (if aplicable) What mobile OS device are you using?

None

**Comment by Sanher** [comment]
Seems that now is working. Closing it. FYI @MooncatDEXT
