### ISSUE TITLE
[BUG] reactivating price alerts fails due to null "createdat"

### ISSUE THREAD

**Issue by Flamingobingo035** [dextools-io/community-requests#104]
### Steps

...
reactivating price alerts fails due to null "createdat".  Setting new alerts was fine.  Only experienced so far on eth main.  See pictures for dev console to show payload info and error response.  Seems like the reactivation api call is trying to provide a null due to that field name not being provided.  The api call before it does pull that data fine for the same alert.

![20240314_130324](https://github.com/dextools-io/community-requests/assets/155481383/a8ce6db8-d3c1-4db0-9891-d1fabd7d4e4f)
![20240314_130313](https://github.com/dextools-io/community-requests/assets/155481383/33f456f9-fdec-4234-9813-d26a7000adf7)
![20240314_130303](https://github.com/dextools-io/community-requests/assets/155481383/d134af4b-4c6d-4f0d-8b3f-11255567f669)

### Which device are you using

- [X] Any
- [ ] Desktop Windows
- [ ] Desktop MacOS
- [ ] Desktop Linux
- [ ] Mobile browser
- [ ] App

### (if aplicable) In which browsers are you seeing the problem?

Chrome

### (if aplicable) What mobile OS device are you using?

None

**Comment by Sanher** [comment]
Should be fixed. Closing. FYI @Flamingobingo035
