### ISSUE TITLE
[FEATURE] Ability to see full tx history in pair explorer wallet filter mode

### ISSUE THREAD

**Issue by Flamingobingo035** [dextools-io/community-requests#105]
### What will you like to see on Dextools?

...
There is a filter option in pair explorer to see only a specific wallets trade history.  This only returns a very very limited tx history on any pair that has volume which renders it useless.

When the filter option is clicked, it shouldnt use the existing history on the screen to filter but actually go back out to etherscan (or whatever block explorer) to return all txs for that specific wallet and token.  

### Why is this a good adding to Dextools?

This will allow a full picture evaluating a wallets trade history on that token and return accurate pnl data which dexscreener currently does.  Without this, that filter option is completely useless on any pair with volume.  Those with minimal volume has some use, but will still leave out trades from long ago which requires manual effort to go to block explorer.

**Comment by Sanher** [comment]
Its in process to be made. FYI @Flamingobingo035
