### ISSUE TITLE
[BUG] Pool creation date is missing

### ISSUE THREAD

**Issue by MooncatDEXT** [dextools-io/community-requests#110]
### Steps

...
https://www.dextools.io/app/en/ether/pair-explorer/0xe6c9774f18c11ebe7b993093da432bcc422bec26

<img width="258" alt="Screenshot 2024-03-26 at 15 42 29" src="https://github.com/dextools-io/community-requests/assets/155443659/94b6cd4c-3110-4ac4-b6ad-6fa6bb67f316">

### Which device are you using

- [X] Any
- [ ] Desktop Windows
- [ ] Desktop MacOS
- [ ] Desktop Linux
- [ ] Mobile browser
- [ ] App

### (if aplicable) What mobile OS device are you using?

None

**Comment by Sanher** [comment]
duplicated from #51 . Closing FYI @MooncatDEXT
