### ISSUE TITLE
[BUG] Token is not findable on Dextools

### ISSUE THREAD

**Issue by MooncatDEXT** [dextools-io/community-requests#113]
### Steps

...
The token is not findable on Dextools. MRINC on Pulsechain.

Ticker: $MRINC
Contract address: 0xfd71636e0ec2cb2307ed5b790b13249bc6ef1be2
Pair address: 0x154c6f3072506288f05042bb6287fe926bca62e4

CMC dexscan: https://coinmarketcap.com/dexscan/pulsechain/0x154c6f3072506288f05042bb6287fe926bca62e4/

### Which device are you using

- [X] Any
- [ ] Desktop Windows
- [ ] Desktop MacOS
- [ ] Desktop Linux
- [ ] Mobile browser
- [ ] App

### (if aplicable) What mobile OS device are you using?

None

**Comment by doughboi96** [comment]
As stated above our correct token pair pool should be 0x154c6f3072506288f05042bB6287Fe926Bca62E4. Currently a token pair for our contract does not exist on Dextools, even though we index on multiple other places i.e. dexscreener, coingecko ect. 
The aggregator on Dextools is pulling the token pair 0x4ffb5c0b47be8f19c754917bb7d57de5d12492ef, and I think its because both contracts share the same Ticker on PulseX. 
![photo_2024-03-27_05-07-55](https://github.com/dextools-io/community-requests/assets/165163036/73b513a7-94a7-4c77-99fa-1ba7f240ae69)

**Comment by doughboi96** [comment]
This is what happens when we search for our contract: 
![image](https://github.com/dextools-io/community-requests/assets/165163036/0333dd39-cc26-468b-83be-798d15c22133)

**Comment by doughboi96** [comment]
Additionally I submitted the form for the only token pair on Dextools by searching MRINC directly. The only token pair that showed was the incorrect pair. I didn't think anything of it, but you'll clearly see the pools don't match. 
![image](https://github.com/dextools-io/community-requests/assets/165163036/d7ad4eed-2eab-4d8f-91a2-b7fb89f2aec4)

**Comment by doughboi96** [comment]
Here you can see our correct pool, and the incorrect pool. Thank you for the consideration in the matter. I know my community greatly appreciates it. Visibility is important to a project. 
![image](https://github.com/dextools-io/community-requests/assets/165163036/19988714-ccb2-4a52-8765-1c44d2393a75)

**Comment by Sanher** [comment]
Linked to dextools-io/backend#548

**Comment by doughboi96** [comment]
Is there a time-frame on how long this might take? Days or weeks? I'm impartial to either but a rough estimate would help. I need to follow up with my team so we can plan accordingly. ect.

**Comment by doughboi96** [comment]
Just a heads up. Someone has attempted to create duplicate scam of our token at https://www.dextools.io/app/en/pulse/pair-explorer/0x2f00d7f77deb16a94607c792bf4b886a0ccb12b5?t=1712327066866

Our token is still CA 0xFd71636E0ec2cB2307eD5b790B13249Bc6ef1Be2
Token pair is still 0x154c6f3072506288f05042bB6287Fe926Bca62E4

I know you guys are busy, but wanted to keep the confusion to a minimum. Thanks again for your help!

**Comment by doughboi96** [comment]
With all due respect its been almost 3 weeks now. Is anyone actually working on this issue???

**Comment by Sanher** [comment]
Fixed
