### ISSUE TITLE
[BUG] DEXTscore issues

### ISSUE THREAD

**Issue by MooncatDEXT** [dextools-io/community-requests#117]
### Steps

The score seems to be wrong. Audit only 4 points.

TOSHI on BASE
https://www.dextools.io/app/en/base/pair-explorer/0xbfc74e1de81e81b0a807469502f6662cc238795e?t=1711813164771
![Uploading Screenshot 2024-03-30 at 16.42.39.png…]()

### Which device are you using

- [X] Any
- [ ] Desktop Windows
- [ ] Desktop MacOS
- [ ] Desktop Linux
- [ ] Mobile browser
- [ ] App

### (if aplicable) What mobile OS device are you using?

None

**Comment by Sanher** [comment]
Seem to have a lot of alerts for both Auditers
