### ISSUE TITLE
[BUG] SSNC token shows contract address of other token as pair address. 

### ISSUE THREAD

**Issue by MooncatDEXT** [dextools-io/community-requests#122]
### Steps

Tokenticker: SSNC 
Contract address: 0x6715515f5aa98e8bd3624922e1ba91e6f5fc4402

Dextools link containing the correct contract address, leads to a not launched token flagged as honeypot: https://www.dextools.io/app/en/ether/pair-explorer/0x6715515f5aa98e8bd3624922e1ba91e6f5fc4402

This is the correct token for this contract address mentioned above: https://www.dextools.io/app/en/ether/pair-explorer/0x02b9e949ba711523ee0f10470d09b47c64d7a46d

### Which device are you using

- [X] Any
- [ ] Desktop Windows
- [ ] Desktop MacOS
- [ ] Desktop Linux
- [ ] Mobile browser
- [ ] App

### (if aplicable) What mobile OS device are you using?

None

**Comment by Sanher** [comment]
We will investigate a possible solution to this cases. dextools-io/backend#587

**Comment by Sanher** [comment]
We have deployed a solution
