### ISSUE TITLE
[BUG] In the 'other pairs' section logos not showing

### ISSUE THREAD

**Issue by MooncatDEXT** [dextools-io/community-requests#13]
### Discussed in https://github.com/dextools-io/community-requests/discussions/11

<div type='discussions-op-text'>

<sup>Originally posted by **MooncatDEXT** January 12, 2024</sup>
### Steps

```bash
...
In the 'other pairs' section, the logo appears only for the manually updated pair. For the remaining pairs, the logo is not displayed.

Example: https://www.dextools.io/app/en/ether/pair-explorer/0x01a8227d4e7c3068ad1000c97a059af5c5fa3476
click on the icon to see 'other pairs'.
```

### Which device are you using

- [x] Desktop Windows
- [x] Desktop MacOS
- [x] Desktop Linux
- [x] Mobile browser
- [x] App

### (if aplicable) What mobile OS device are you using?

None

### In which page do you see the problem?

https://www.dextools.io/app/en/ether/pair-explorer/0x01a8227d4e7c3068ad1000c97a059af5c5fa3476

### Additional Info

_No response_</div>

**Comment by Sanher** [comment]
@MooncatDEXT seems to have been fixed, could you check?
<img width="571" alt="Captura de pantalla 2024-02-07 a las 14 59 17" src="https://github.com/dextools-io/community-requests/assets/13277368/5616bd26-5f13-4b2d-9bf3-1afea6922b88">

**Comment by Sanher** [comment]
Fixed. Closing
