### ISSUE TITLE
[BUG] Token showing 0 Marketcap

### ISSUE THREAD

**Issue by MooncatDEXT** [dextools-io/community-requests#132]
### Steps

https://www.dextools.io/app/en/ether/pair-explorer/0x189967a947c0133de1eac4f931ddc901b0262790?t=1716594988159

<img width="235" alt="Screenshot 2024-05-25 at 01 58 24" src="https://github.com/dextools-io/community-requests/assets/155443659/b1aacb84-9b36-442d-af4a-f85474189aaa">

### Which device are you using

- [X] Any
- [ ] Desktop Windows
- [ ] Desktop MacOS
- [ ] Desktop Linux
- [ ] Mobile browser
- [ ] App

### (if aplicable) What mobile OS device are you using?

None

**Comment by Sanher** [comment]
Linked to dextools-io/backend#673

**Comment by Sanher** [comment]
Fixed
