### ISSUE TITLE
[Bug] Shibarium charts not displaying

### ISSUE THREAD

**Issue by MooncatDEXT** [dextools-io/community-requests#44]
### Steps

```bash
...
Since 16th of december, Shibarium charts are not displaying any data.
```

### Which device are you using

- [X] Desktop Windows
- [X] Desktop MacOS
- [X] Desktop Linux
- [X] Mobile browser
- [X] App

### (if aplicable) What mobile OS device are you using?

None

### In which page do you see the problem?

https://www.dextools.io/app/en/shibarium

**Comment by Sanher** [comment]
Seems to have ben updated and its fixed. FYI @MooncatDEXT
