### ISSUE TITLE
[BUG] Price alerts immediately trigger 1st time setup on a token that had none

### ISSUE THREAD

**Issue by Sanher** [dextools-io/community-requests#47]
### Discussed in https://github.com/dextools-io/community-requests/discussions/46

<div type='discussions-op-text'>

<sup>Originally posted by **Flamingobingo035** January 19, 2024</sup>
### Steps

...
Take any token on any chain thats never had price alerts setup for it yet.  Add 2 alerts, 1 plenty under the price, 1 plenty over the price.  The very next tx will cause at least one of them to immediately trigger even though the price is no where near it.  Its a one time thing per token but it happens on every token the same way for the last 6-12 months.

### Which device are you using

- [X] Desktop Windows
- [ ] Desktop MacOS
- [ ] Desktop Linux
- [X] Mobile browser
- [ ] App

### (if aplicable) In which browsers are you seeing the problem?

Chrome

### (if aplicable) What mobile OS device are you using?

Android

### In which page do you see the problem?

Any token at all (see steps)

### Additional Info

_No response_</div>

**Comment by Sanher** [comment]
Linked to issue dextools-io/back#257

**Comment by Flamingobingo035** [comment]
Any update on this one?  With it being really easy to consistently reproduce, i want to believe its a quick one to resolve

**Comment by Sanher** [comment]
Fixed. FYI @Flamingobingo035
