### ISSUE TITLE
[BUG] wrong liquidity shown, 5k instead 790k

### ISSUE THREAD

**Issue by GuillermoDextools** [dextools-io/community-requests#49]
### Steps

...
https://www.dextools.io/app/en/solana/pair-explorer/8rTxNTDT73mRhYgpJj6djghEN5jVe6kpeL7NR3W2Uvdr
https://dexscreener.com/solana/8rtxntdt73mrhygpjj6djghen5jve6kpel7nr3w2uvdr

### Which device are you using

- [ ] Desktop Windows
- [ ] Desktop MacOS
- [ ] Desktop Linux
- [ ] Mobile browser
- [ ] App

### (if aplicable) What mobile OS device are you using?

None

**Comment by Sanher** [comment]
Linked to dextools-io/backend#407

**Comment by Sanher** [comment]
Fixed
