### ISSUE TITLE
[BUG] Token (TUCKER) is not findable in the Searchbar

### ISSUE THREAD

**Issue by MooncatDEXT** [dextools-io/community-requests#65]
### Steps

...
The token TUCKER CARLSON (TUCKER) is not findable in the Searchbar by name.

https://www.dextools.io/app/en/ether/pair-explorer/0x4a885a72c45b2dd9fef6d732b3de7baaf9e5436c?t=1707367877541

### Which device are you using

- [X] Any
- [ ] Desktop Windows
- [ ] Desktop MacOS
- [ ] Desktop Linux
- [ ] Mobile browser
- [ ] App

### (if aplicable) What mobile OS device are you using?

None

**Comment by Sanher** [comment]
Problem was detected for some stable pairs, fixed. @MooncatDEXT
