### ISSUE TITLE
[BUG] Token (TRUMP) is not findable in the Searchbar

### ISSUE THREAD

**Issue by MooncatDEXT** [dextools-io/community-requests#66]
### Steps

...
The token MAGA (TRUMP) is not findable in the Searchbar by searching for 'TRUMP'.

https://www.dextools.io/app/en/ether/pair-explorer/0xe4b8583ccb95b25737c016ac88e539d0605949e8?t=1707368187197

### Which device are you using

- [X] Any
- [ ] Desktop Windows
- [ ] Desktop MacOS
- [ ] Desktop Linux
- [ ] Mobile browser
- [ ] App

### (if aplicable) What mobile OS device are you using?

None

**Comment by Sanher** [comment]
Problem was detected for some stable pairs, fixed. @MooncatDEXT
