### ISSUE TITLE
[BUG] Token (HUNDRED) is not findable in the Searchbar

### ISSUE THREAD

**Issue by MooncatDEXT** [dextools-io/community-requests#67]
### Steps

...
The token HUNDRED (HUNDRED) is not findable in the Searchbar by name.

**ERC20 token:** https://www.dextools.io/app/en/ether/pair-explorer/0xecb037578a1c3e58b91e193970ad9f19ccca2b48?t=1707348684958
**BEP20 token:** https://www.dextools.io/app/en/bnb/pair-explorer/0x5a1c486edefda2f09d3b349fadc38524f1743826?t=1707348803200

### Which device are you using

- [X] Any
- [ ] Desktop Windows
- [ ] Desktop MacOS
- [ ] Desktop Linux
- [ ] Mobile browser
- [ ] App

### (if aplicable) What mobile OS device are you using?

None

**Comment by Sanher** [comment]
Problem was detected for some stable pairs, fixed. @MooncatDEXT
