### ISSUE TITLE
[BUG] Creation Date and TF lock are not correct for Arbitrum pair Hamachi

### ISSUE THREAD

**Issue by GuillermoDextools** [dextools-io/community-requests#70]
### Steps

...
creation 0 for a pair created on 2023
lock on team finance not showing
https://www.dextools.io/app/en/arbitrum/pair-explorer/0x8e89f6d18086bcb660826b6de0e2a178f6155153?t=1707591404656
https://www.team.finance/view-coin/0x02150e97271fDC0D6E3A16d9094A0948266F07dD?name=Hamachi&symbol=HAMI&chainid=0xa4b1

### Which device are you using

- [ ] Any
- [ ] Desktop Windows
- [ ] Desktop MacOS
- [ ] Desktop Linux
- [ ] Mobile browser
- [ ] App

### (if aplicable) What mobile OS device are you using?

None

**Comment by Sanher** [comment]
Closing in favor of #45
