### ISSUE TITLE
[BUG] Holders for token (DRAGY) on Solana not displaying

### ISSUE THREAD

**Issue by MooncatDEXT** [dextools-io/community-requests#81]
### Steps

...
The number of holders for DRAGY on the Solana blockchain is not displayed.

### Which device are you using

- [X] Any
- [ ] Desktop Windows
- [ ] Desktop MacOS
- [ ] Desktop Linux
- [ ] Mobile browser
- [ ] App

### (if aplicable) What mobile OS device are you using?

None

### In which page do you see the problem?

https://www.dextools.io/app/en/solana/pair-explorer/9AJZ6VuT3RgH6d3NQF9iocBHG7X1VSrZrkT3SP47oZAF

**Comment by Sanher** [comment]
Fixed on 24/02/15 all the tokens in Solana have accurate holders now.
