### ISSUE TITLE
[BUG] Liquidity lock (BIGMIKE) not showing correctly

### ISSUE THREAD

**Issue by MooncatDEXT** [dextools-io/community-requests#83]
### Steps

...
The liquidity lock is showing incorrectly for this token (100% of LP is locked, the green circle shows a low amount locked): https://www.dextools.io/app/en/ether/pair-explorer/0x41b3308c4dfbca2d4d35037bb7405c5e51284203

Lock on pinksale: https://www.pinksale.finance/pinklock/record/1016874?chain=ETH

### Which device are you using

- [x] Any
- [ ] Desktop Windows
- [ ] Desktop MacOS
- [ ] Desktop Linux
- [ ] Mobile browser
- [ ] App

### (if aplicable) What mobile OS device are you using?

None

**Comment by Sanher** [comment]
This lock is showing the appropiate info. We dont kwon how much of the pairs are lock because we dont have the total number of tokens in the data we get from Pinksale, we only show the small percatage that is token locked in which we are able to calculate the percentage.
