### ISSUE TITLE
[BUG] Alphabetical sorting of favorites is not working properly

### ISSUE THREAD

**Issue by MooncatDEXT** [dextools-io/community-requests#86]
### Steps

...
Favorites are being sorted incorrectly. When sorting by name, there are tokens that are sorted in the wrong position.
It happens more with long favorites lists.

Examples:
![photo_2024-02-24 06 51 19](https://github.com/dextools-io/community-requests/assets/155443659/af20f92f-4972-4a1c-9af3-14872846b025)

<img width="292" alt="Screenshot 2024-02-24 at 06 55 07" src="https://github.com/dextools-io/community-requests/assets/155443659/2efd9670-479a-43cc-81ba-a026b2b3d46e">

<img width="299" alt="Screenshot 2024-02-24 at 06 55 57" src="https://github.com/dextools-io/community-requests/assets/155443659/a3a659c7-4fb4-478a-bbe1-ca95b44c1996">

### Which device are you using

- [ ] Any
- [ ] Desktop Windows
- [ ] Desktop MacOS
- [ ] Desktop Linux
- [ ] Mobile browser
- [ ] App

### (if aplicable) What mobile OS device are you using?

None

**Comment by Sanher** [comment]
Linked to dextools-io/frontend#1906

**Comment by Sanher** [comment]
Fixed. FYI @MooncatDEXT
