### ISSUE TITLE
[BUG] Liquidity and other pool data doesn't fetch for ECLIP on Arbitrum (Camelot Algebra pool)

### ISSUE THREAD

**Issue by MooncatDEXT** [dextools-io/community-requests#98]
### Steps

...
The following data doesn't show, which results in a low DEXTscore: Liquidity, Total tx, Pool created, Pooled WETH, Pooled ECLIP.

LP: https://info.camelot.exchange/pair/v3/0x264bd241fcc0fa14803db2930d6bdbc6661afc27

https://www.dextools.io/app/en/arbitrum/pair-explorer/0x264bd241fcc0fa14803db2930d6bdbc6661afc27?t=1709892335843

<img width="247" alt="Screenshot 2024-03-08 at 11 06 50" src="https://github.com/dextools-io/community-requests/assets/155443659/af2d4e9e-4455-466e-8c65-43da05a71aec">

<img width="239" alt="Screenshot 2024-03-08 at 11 08 28" src="https://github.com/dextools-io/community-requests/assets/155443659/329e5730-1833-4339-8f4a-9f2ac78f1b20">

### Which device are you using

- [X] Any
- [ ] Desktop Windows
- [ ] Desktop MacOS
- [ ] Desktop Linux
- [ ] Mobile browser
- [ ] App

### (if aplicable) What mobile OS device are you using?

None

**Comment by Sanher** [comment]
Linked to dextools-io/backend#228 and dextools-io/backend#241

**Comment by MooncatDEXT** [comment]
HAMI token doens't pull tx count in pool info.

https://www.dextools.io/app/en/solana/pair-explorer/84Nu43GsHLaCDuVSvgiTwpQDTNhYejKFEkJmeXBFJmqQ

<img width="252" alt="Screenshot 2024-03-10 at 21 41 10" src="https://github.com/dextools-io/community-requests/assets/155443659/4188a166-0009-42bb-b68d-828a4c201c66">

**Comment by MooncatDEXT** [comment]
Liquidity, total transactions, pool created and pooled tokens not showing on GLEND on Arbitrum, Camelot Algebra pool.

https://www.dextools.io/app/en/arbitrum/pair-explorer/0xe9d3e6811d1be8ba40a9273ebec6ff09fe2a6741?t=1711360150369

<img width="262" alt="Screenshot 2024-03-25 at 10 51 37" src="https://github.com/dextools-io/community-requests/assets/155443659/d0c36d5f-c7c5-4a2c-ad64-e71ccd52223f">

**Comment by Sanher** [comment]
> HAMI token doens't pull tx count in pool info.
> 
> https://www.dextools.io/app/en/solana/pair-explorer/84Nu43GsHLaCDuVSvgiTwpQDTNhYejKFEkJmeXBFJmqQ
> 
> <img alt="Screenshot 2024-03-10 at 21 41 10" width="252" src="https://private-user-images.githubusercontent.com/155443659/311542917-4188a166-0009-42bb-b68d-828a4c201c66.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTEzOTQ4NjYsIm5iZiI6MTcxMTM5NDU2NiwicGF0aCI6Ii8xNTU0NDM2NTkvMzExNTQyOTE3LTQxODhhMTY2LTAwMDktNDJiYi1iNjhkLTgyOGE0YzIwMWM2Ni5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzI1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMyNVQxOTIyNDZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lYzE5ZWI3NzNhZGUzZmMzMGZiZGYzNzU2ZDZiYjlmNTA5MWY0MWM3NTNhNGI1OTM2MGU3NzdkYzRhYTRkNzczJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.IMNPN_3T1FdRS7V_4mWJCPtR7uHX6zrMb216w1n3lbc">

this is not in Cameleot right?

**Comment by Sanher** [comment]
Fixed
